"""W38: PostgreSQL path (DBS-05), deployment packaging (OPS-04), compliance monitoring (SEC-05),
data privacy (ENT-17), mobile / PWA (ENT-09), regulatory pack register (ENT-14)."""

import pytest


# ── DBS-05 ──
def test_translate_core_constructs():
    from db.postgres import translate
    assert translate("SELECT * FROM t WHERE a=? AND b LIKE '%x?%'") == \
        "SELECT * FROM t WHERE a=%s AND b ILIKE '%%x?%%'"                    # ? in a literal stays
    assert translate("INSERT OR IGNORE INTO t (a) VALUES (?)").endswith("ON CONFLICT DO NOTHING")
    assert "string_agg(DISTINCT CAST(f AS text), ',')" in translate("SELECT GROUP_CONCAT(DISTINCT f) FROM t")
    assert translate("SELECT MAX(a), MAX(a, b), MIN(x, 0) FROM t") == "SELECT MAX(a), GREATEST(a, b), LEAST(x, 0) FROM t"
    assert translate("SELECT 1 WHERE d >= date(?, '-30 days')") == \
        "SELECT 1 WHERE d >= CAST(CAST(%s AS date) - INTERVAL '30 day' AS date)"
    assert translate("SELECT date('now')") == "SELECT CURRENT_DATE"
    assert translate("SELECT IFNULL(a, 0) FROM t WHERE n NOT LIKE ?") == "SELECT COALESCE(a, 0) FROM t WHERE n NOT ILIKE %s"


def test_replace_uses_the_unique_key_the_insert_covers():
    from db.postgres import translate, UnsupportedSQL
    keys = {"fii": [["id"], ["date"]]}                                      # surrogate id + UNIQUE(date)
    out = translate("INSERT OR REPLACE INTO fii (date, net) VALUES (?, ?)", lambda t: keys[t])
    assert out.endswith("ON CONFLICT (date) DO UPDATE SET net=EXCLUDED.net")
    with pytest.raises(UnsupportedSQL, match="no primary / unique key"):
        translate("INSERT OR REPLACE INTO fii (net) VALUES (?)", lambda t: keys[t])


def test_upsert_right_hand_columns_are_qualified():
    from db.postgres import translate
    out = translate("INSERT INTO s (day, ticks, n) VALUES (?,?,?) ON CONFLICT(day) DO UPDATE SET "
                    "ticks=ticks+excluded.ticks, n=MAX(n, excluded.n)")
    assert "ticks=s.ticks+excluded.ticks" in out and "n=GREATEST(s.n, excluded.n)" in out


def test_sqlite_only_constructs_fail_loudly_or_map_to_the_catalog():
    from db.postgres import translate, UnsupportedSQL
    assert translate("SELECT * FROM led l ORDER BY d, l.rowid LIMIT ?") == "SELECT * FROM led l ORDER BY d, l.ctid LIMIT %s"
    for sql in ("PRAGMA index_list(t)", "SELECT rowid FROM t", "SELECT strftime('%Y', d) FROM t"):
        with pytest.raises(UnsupportedSQL):
            translate(sql)
    ti = translate('PRAGMA table_info("prices")')
    assert "information_schema.columns" in ti and "table_name='prices'" in ti and "AS pk" in ti
    m = translate("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? AND name NOT LIKE 'sqlite_%'")
    assert "information_schema.tables" in m and "name=%s" in m and "'sqlite_%%'" in m
    assert translate("PRAGMA journal_mode=WAL") == "SELECT 'wal' AS journal_mode"
    s = translate("SELECT SUM(a IS NULL), SUM(CASE WHEN b=1 THEN 1 ELSE 0 END), SUM(q), AVG(x > (y + 1)) FROM t")
    assert s == ("SELECT SUM(CAST((a IS NULL) AS INT)), SUM(CASE WHEN b=1 THEN 1 ELSE 0 END), SUM(q), "
                 "AVG(CAST((x > (y + 1)) AS INT)) FROM t")


def test_ddl_and_append_only_triggers():
    from db.postgres import ddl, trigger_ddl, keys_from_ddl, UnsupportedSQL
    d = ddl("CREATE TABLE t (id INTEGER PRIMARY KEY, v REAL, b BLOB, at TEXT DEFAULT (datetime('now')), "
            "n TEXT COLLATE NOCASE)")
    assert "id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in d and "DOUBLE PRECISION" in d
    assert "BYTEA" in d and "DEFAULT CURRENT_TIMESTAMP" in d and "COLLATE" not in d
    t = trigger_ddl("CREATE TRIGGER g BEFORE DELETE ON led WHEN OLD.tenant_id <> 'uat' "
                    "BEGIN SELECT RAISE(ABORT, 'led is append-only'); END")
    assert t == ("CREATE TRIGGER g BEFORE DELETE ON led FOR EACH ROW WHEN (OLD.tenant_id <> 'uat') "
                 "EXECUTE FUNCTION atip_append_only('led is append-only')")
    with pytest.raises(UnsupportedSQL):
        trigger_ddl("CREATE TRIGGER x AFTER INSERT ON t BEGIN UPDATE t SET a=1; END")
    k = keys_from_ddl(["CREATE TABLE IF NOT EXISTS a (id INTEGER PRIMARY KEY AUTOINCREMENT, d DATE, UNIQUE(d))",
                       "CREATE TABLE b (x TEXT, y TEXT, PRIMARY KEY (x, y))",
                       "CREATE UNIQUE INDEX IF NOT EXISTS ux ON a(d, id)"])
    assert k["a"][0] == ["id"] and ["d"] in k["a"] and ["d", "id"] in k["a"] and k["b"] == [["x", "y"]]


def test_scanner_reports_the_work_list(tmp_path):
    from db.dialect_scan import scan
    (tmp_path / "m.py").write_text(
        'SCHEMA = "CREATE TABLE IF NOT EXISTS k (id INTEGER PRIMARY KEY, d DATE UNIQUE)"\n'
        'def f(c, t):\n'
        '    c.execute("SELECT * FROM k WHERE d=?", (1,))\n'
        '    c.execute(f"SELECT * FROM {t} WHERE d LIKE ?", ("x",))\n'
        '    c.execute("INSERT OR REPLACE INTO k (d) VALUES (?)", (1,))\n'
        '    c.execute("PRAGMA index_list(k)")\n'
        '    c.execute("PRAGMA table_info(k)")\n', encoding="utf-8")
    r = scan(tmp_path)
    assert (r["statements"], r["translatable"], r["needs_change"]) == (5, 4, 1)
    assert r["by_kind"] == {"PRAGMA": 1} and r["items"][0]["line"] == 6


def test_runtime_stays_on_sqlite_unless_all_three_switches(monkeypatch, tmp_path):
    import db.schema as S
    monkeypatch.chdir(tmp_path)
    (tmp_path / "atip_data").mkdir()
    cfg = tmp_path / "atip_data" / "config.json"
    monkeypatch.setenv("ATIP_DATABASE_URL", "postgresql://u@127.0.0.1:1/x")
    for body, expect in (('{"database": {"backend": "postgresql"}}', None),
                         ('{"database": {"backend": "postgresql", "allow_experimental": true}}',
                          "postgresql://u@127.0.0.1:1/x")):
        cfg.write_text(body, encoding="utf-8")
        monkeypatch.setattr(S, "_PG_URL", [])
        assert S.pg_runtime_url() == expect
    monkeypatch.setenv("ATIP_DATABASE_URL", "")
    monkeypatch.setenv("DATABASE_URL", "postgresql://other-project/db")          # a stray URL is ignored
    monkeypatch.setattr(S, "_PG_URL", [])
    assert S.pg_runtime_url() is None
