"""
db/sql/ schema scripts (tools/schema_sql.py).

The scripts are generated from ATIP's own start-up code, never hand-written, so
they can be held to it: a schema change that does not regenerate them fails here
rather than shipping a script that builds last month's database. (The old files
were dumped once and drifted -- "W39 is not in these files yet".)

The PostgreSQL load test needs a server and is skipped unless
ATIP_TEST_POSTGRES_URL is set (see tests/test_postgres_backend.py). It uses a
database named after that URL's with "_schema" appended, DROPped and recreated.
"""

import os
import sqlite3
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))

import schema_sql  # noqa: E402

LIVE_URL = os.environ.get("ATIP_TEST_POSTGRES_URL")


@pytest.fixture(scope="module")
def generated():
    return schema_sql.generate()


def test_the_checked_in_scripts_match_the_generator(generated):
    pg, lite = generated
    for path, text in ((schema_sql.PG_FILE, pg), (schema_sql.SQLITE_FILE, lite)):
        assert path.read_text(encoding="utf-8") == text, \
            f"{path.relative_to(ROOT)} is stale: run `python tools/schema_sql.py` and commit the result"


def test_there_is_no_mysql_script_any_more():
    """PostgreSQL is the one server database; the phpMyAdmin export went with the MySQL backend."""
    assert sorted(p.name for p in (ROOT / "db" / "sql").glob("*.sql")) == \
        ["atip_schema.postgresql.sql", "atip_schema.sqlite.sql"]


def test_the_sqlite_script_builds_the_database_init_db_would(tmp_path, monkeypatch, generated):
    db = tmp_path / "atip.db"
    c = sqlite3.connect(db)
    c.executescript(generated[1])
    c.close()

    def objects():
        with sqlite3.connect(db) as k:
            return k.execute("SELECT type, name, sql FROM sqlite_master ORDER BY type, name").fetchall()

    before = objects()
    assert sum(1 for t, _, _ in before if t == "table") > 200
    import db.schema as S
    monkeypatch.setattr(S, "DB_PATH", db)
    S.init_db()
    from ops import migrations
    conn = S.get_connection()
    try:
        assert migrations.validate(conn) == [] and migrations.apply(conn) == []   # recorded as current
        assert conn.execute("SELECT COUNT(*) FROM weight_config").fetchone()[0] > 100
    finally:
        conn.close()
    assert objects() == before                                                    # nothing left to add


def test_the_postgresql_script_is_translated_by_the_runtime_code(generated):
    pg = generated[0]
    assert "AUTOINCREMENT" not in pg and " REAL" not in pg and "RAISE(ABORT" not in pg
    assert "atip_append_only" in pg and "GENERATED BY DEFAULT AS IDENTITY" in pg
    assert pg.count("CREATE TABLE IF NOT EXISTS") == generated[1].count("\nCREATE TABLE ")


@pytest.mark.skipif(not LIVE_URL, reason="set ATIP_TEST_POSTGRES_URL to run live PostgreSQL tests")
def test_the_postgresql_script_loads_into_an_empty_database(generated):
    psycopg = pytest.importorskip("psycopg")
    from urllib.parse import urlparse, urlunparse
    u = urlparse(LIVE_URL)
    name = (u.path or "/atip_test").lstrip("/") + "_schema"
    url = urlunparse(u._replace(path="/" + name))
    with psycopg.connect(urlunparse(u._replace(path="/postgres")), autocommit=True) as c:
        c.execute(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)')
        c.execute(f'CREATE DATABASE "{name}"')
    with psycopg.connect(url, autocommit=True) as c:
        c.execute(generated[0])
        tables = c.execute("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='public' "
                           "AND table_type='BASE TABLE'").fetchone()[0]
        assert tables == generated[1].count("\nCREATE TABLE ")
        assert c.execute("SELECT COUNT(*) FROM pg_trigger WHERE NOT tgisinternal").fetchone()[0] == \
            generated[1].count("\nCREATE TRIGGER ")
        assert c.execute("SELECT COUNT(*) FROM weight_config").fetchone()[0] > 100
        # the seeded ids were followed by a sequence reset, so the next row does not collide
        c.execute("INSERT INTO weight_config (index_name, variable, weight) VALUES ('T', 'T', 0.1)")
        # an append-only guard fires
        c.execute("INSERT INTO perf_ledger_void (txn_id, tenant_id, owner_id, reason, voided_at) "
                  "VALUES ('t1', 'default', 'owner', 'test', CURRENT_TIMESTAMP)")
        with pytest.raises(psycopg.errors.RaiseException, match="append-only"):
            c.execute("DELETE FROM perf_ledger_void WHERE txn_id='t1'")
