"""
Strategy lifecycle (SE-09) and the strategy event log.

States
    DRAFT       being written; not run on a schedule
    RESEARCH    being researched
    BACKTEST    under backtest
    VALIDATION  under out-of-sample validation
    APPROVED    validation passed
    PAPER       decisions generated daily against the PAPER book
    READY       ready for activation
    ACTIVE      decisions generated daily against the LIVE book -- intents only,
                NOT_AUTHORIZED; execution is W4
    PAUSED      temporarily stopped; returns to where it was
    DISABLED    switched off (e.g. faulty); can be re-enabled
    RETIRED     no longer used; takes no new versions
    ARCHIVED    retired and archived (terminal)

TRANSITIONS lists every allowed move; anything else is refused with the list of
allowed targets. The short route DRAFT -> ACTIVE is allowed, so the research
states are available but not mandatory -- but ACTIVE always needs evidence:

    -> VALIDATION  a COMPLETED backtest of the current version
    -> APPROVED    a COMPLETED validation/test window or walk-forward run
    -> ACTIVE      a COMPLETED backtest of the current version

Versions are immutable (registry.py); the first activation of a version is
stamped on it (first_activated_at), so "the version that was active" is
always identifiable.

Every transition -- and every error the engine records against a strategy --
is a row in strategy_engine_event (event_type LIFECYCLE / VERSION / ERROR /
DECISION_RUN), never an in-place edit. strategy_event is a different table:
the aggressive-exit module's position ledger.
"""

from __future__ import annotations

import json
from datetime import datetime

STATES = ("DRAFT", "RESEARCH", "BACKTEST", "VALIDATION", "APPROVED", "PAPER", "READY", "ACTIVE",
          "PAUSED", "DISABLED", "RETIRED", "ARCHIVED")
_ALWAYS = {"DISABLED", "RETIRED"}
TRANSITIONS = {
    "DRAFT":      {"RESEARCH", "BACKTEST", "ACTIVE"} | _ALWAYS,
    "RESEARCH":   {"BACKTEST", "DRAFT", "ACTIVE"} | _ALWAYS,
    "BACKTEST":   {"VALIDATION", "RESEARCH", "ACTIVE"} | _ALWAYS,
    "VALIDATION": {"APPROVED", "BACKTEST", "RESEARCH", "ACTIVE"} | _ALWAYS,
    "APPROVED":   {"PAPER", "READY", "VALIDATION", "ACTIVE"} | _ALWAYS,
    "PAPER":      {"READY", "ACTIVE", "PAUSED", "APPROVED"} | _ALWAYS,
    "READY":      {"ACTIVE", "PAPER", "PAUSED"} | _ALWAYS,
    "ACTIVE":     {"PAUSED"} | _ALWAYS,
    "PAUSED":     {"ACTIVE", "PAPER", "READY"} | _ALWAYS,
    "DISABLED":   {"DRAFT", "PAPER", "ACTIVE", "RETIRED"},
    "RETIRED":    {"ARCHIVED"},
    "ARCHIVED":   set(),
}
DECISION_STATES = ("PAPER", "READY", "ACTIVE")       # decisions generated by the scheduled job
OFF_STATES = ("PAUSED", "DISABLED", "RETIRED", "ARCHIVED")


class LifecycleError(ValueError):
    pass


def log_event(conn, strategy_id, event_type, message="", version=None, details=None, from_state=None,
              to_state=None, actor="system", commit=True):
    conn.execute("INSERT INTO strategy_engine_event (strategy_id,version,event_type,from_state,to_state,message,"
                 "details_json,actor,at) VALUES (?,?,?,?,?,?,?,?,?)",
                 (strategy_id, version, event_type, from_state, to_state, (message or "")[:2000],
                  json.dumps(details or {}, default=str), actor, datetime.now()))
    if commit:
        conn.commit()


def _evidence(conn, strategy_id, version, to_state):
    """(ok, note) for the states that need a backtest behind them."""
    if to_state in ("VALIDATION", "ACTIVE"):
        r = conn.execute("SELECT run_id FROM backtest_run WHERE strategy_id=? AND strategy_version=? "
                         "AND status='COMPLETED' ORDER BY finished_at DESC LIMIT 1", (strategy_id, version)).fetchone()
        return (r is not None), (f"backtest {r[0]}" if r else f"a completed backtest of version {version}")
    if to_state == "APPROVED":
        r = conn.execute("SELECT run_id FROM backtest_run WHERE strategy_id=? AND strategy_version=? "
                         "AND status='COMPLETED' AND (period_label IN ('validation','test') "
                         "OR kind IN ('wf_test','walk_forward')) ORDER BY finished_at DESC LIMIT 1",
                         (strategy_id, version)).fetchone()
        return (r is not None), (f"out-of-sample run {r[0]}" if r else
                                 f"a completed validation/test or walk-forward run of version {version}")
    return True, None


def transition(conn, strategy_id: str, to_state: str, reason: str = "", evidence: dict | None = None,
               actor: str = "owner") -> dict:
    to_state = (to_state or "").upper()
    if to_state not in STATES:
        raise LifecycleError(f"state must be one of {STATES}")
    row = conn.execute("SELECT status, current_version FROM strategy WHERE strategy_id=?", (strategy_id,)).fetchone()
    if not row:
        raise LifecycleError(f"no strategy {strategy_id}")
    frm, version = row[0], row[1]
    if to_state == frm:
        raise LifecycleError(f"{strategy_id} is already {frm}")
    if to_state not in TRANSITIONS[frm]:
        raise LifecycleError(f"{frm} -> {to_state} is not allowed; from {frm}: {sorted(TRANSITIONS[frm]) or 'none'}")
    ok, note = _evidence(conn, strategy_id, version, to_state)
    if not ok:
        raise LifecycleError(f"{frm} -> {to_state} needs {note}")
    ev = dict(evidence or {})
    if note:
        ev.setdefault("check", note)
    now = datetime.now()
    conn.execute("UPDATE strategy SET status=?, updated_at=?" + (", activated_at=?" if to_state == "ACTIVE" else "")
                 + " WHERE strategy_id=?",
                 (to_state, now, now, strategy_id) if to_state == "ACTIVE" else (to_state, now, strategy_id))
    if to_state == "ACTIVE":
        conn.execute("UPDATE strategy_version SET first_activated_at=COALESCE(first_activated_at, ?) "
                     "WHERE strategy_id=? AND version=?", (now, strategy_id, version))
    log_event(conn, strategy_id, "LIFECYCLE", reason, version, ev, frm, to_state, actor, commit=False)
    conn.commit()
    return {"strategy_id": strategy_id, "version": version, "from": frm, "to": to_state, "evidence": ev}


def history(conn, strategy_id, event_type: str | None = "LIFECYCLE", limit: int = 200) -> list:
    q = "SELECT * FROM strategy_engine_event WHERE strategy_id=?"
    args = [strategy_id]
    if event_type:
        q += " AND event_type=?"; args.append(event_type)
    q += " ORDER BY id DESC LIMIT ?"; args.append(int(limit))
    out = []
    for r in conn.execute(q, args):
        d = dict(r)
        d["details"] = json.loads(d.pop("details_json") or "{}")
        out.append(d)
    return out
