"""
PostgreSQL support (W38: DBS-05) -- the path off SQLite, built so it can be taken one step at a time.

ATIP runs on SQLite (WAL) today and keeps doing so by default. This module provides what moving to
Postgres needs, without forcing it:

  translate(sql)        SQLite -> PostgreSQL for the dialect ATIP actually uses (measured with
                        db/dialect_scan.py): ? placeholders, INSERT OR IGNORE, INSERT OR REPLACE (as an
                        upsert on the table's primary key), excluded., date(x, '+/-N unit'), GROUP_CONCAT,
                        2-argument MAX / MIN (-> GREATEST / LEAST), LIKE (case-insensitive in SQLite ->
                        ILIKE). Constructs with no safe automatic translation -- PRAGMA, sqlite_master,
                        rowid, strftime() in SQL -- raise UnsupportedSQL naming the construct, so a missed
                        query fails loudly instead of returning something different.
  ddl(sqlite_create)    a CREATE TABLE / INDEX statement in PostgreSQL types (INTEGER PRIMARY KEY
                        AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY, REAL -> DOUBLE PRECISION,
                        BLOB -> BYTEA)
  PgConnection          a sqlite3-shaped connection over psycopg 3 (execute / executemany / fetchone /
                        fetchall / commit / rollback / close; rows readable by index AND by column name, like
                        sqlite3.Row), translating every statement on the way through.

Activation (db/schema.get_connection): config.json "database": {"backend": "postgres",
"allow_experimental": true} plus a DSN in ATIP_PG_DSN (secret). BOTH are required: until every query has
been exercised on Postgres (tools/pg_migrate.py --check runs the read paths), the backend stays opt-in.
Requires `pip install "psycopg[binary]"` (not installed by default).
"""

from __future__ import annotations

import re


class UnsupportedSQL(ValueError):
    pass


_UNSUPPORTED = [(re.compile(r"^\s*PRAGMA\b", re.I), "PRAGMA"), (re.compile(r"\bsqlite_master\b", re.I), "sqlite_master"),
                (re.compile(r"\browid\b", re.I), "rowid"), (re.compile(r"\bstrftime\s*\(", re.I), "strftime()")]
_UNITS = {"day": "day", "days": "day", "month": "month", "months": "month", "year": "year", "years": "year",
          "hour": "hour", "hours": "hour", "minute": "minute", "minutes": "minute"}


def _split_strings(sql):
    """[(is_string_literal, text)] so rewrites never touch quoted text."""
    out, i, buf = [], 0, []
    while i < len(sql):
        ch = sql[i]
        if ch == "'":
            if buf:
                out.append((False, "".join(buf)))
                buf = []
            j = i + 1
            while j < len(sql):
                if sql[j] == "'" and (j + 1 >= len(sql) or sql[j + 1] != "'"):
                    break
                j += 2 if sql[j] == "'" else 1
            out.append((True, sql[i:j + 1]))
            i = j + 1
            continue
        buf.append(ch)
        i += 1
    if buf:
        out.append((False, "".join(buf)))
    return out


def _date_mod(m):
    arg, sign, n, unit = m.group(1).strip(), m.group(2), m.group(3), m.group(4).lower()
    u = _UNITS.get(unit)
    if not u:
        raise UnsupportedSQL(f"date modifier unit {unit!r}")
    base = "CURRENT_DATE" if arg.lower() in ("'now'",) else f"CAST({arg} AS date)"
    return f"CAST({base} {sign} INTERVAL '{n} {u}' AS date)"


def _greatest(sql):
    """MAX(a, b) / MIN(a, b) with a top-level comma -> GREATEST / LEAST (aggregates untouched)."""
    out, i = [], 0
    pat = re.compile(r"\b(MAX|MIN)\s*\(", re.I)
    while True:
        m = pat.search(sql, i)
        if not m:
            out.append(sql[i:])
            return "".join(out)
        depth, j, comma = 1, m.end(), False
        while j < len(sql) and depth:
            c = sql[j]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
            elif c == "," and depth == 1:
                comma = True
            j += 1
        out.append(sql[i:m.start()])
        out.append(("GREATEST(" if m.group(1).upper() == "MAX" else "LEAST(") if comma else m.group(0))
        i = m.end()


def translate(sql: str, pk_of=None) -> str:
    """SQLite SQL -> PostgreSQL. pk_of(table) -> [pk columns] is needed for INSERT OR REPLACE."""
    for rx, name in _UNSUPPORTED:
        if rx.search(sql):
            raise UnsupportedSQL(f"{name} has no automatic PostgreSQL translation: {sql.strip()[:120]}")
    parts = _split_strings(sql)
    text = "\x00".join(p for s, p in parts if not s)                    # code only, joined by markers
    strings = [p for s, p in parts if s]
    replace_target = None
    m = re.search(r"\bINSERT\s+OR\s+REPLACE\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)", text, re.I)
    if m:
        replace_target = (m.group(1), [c.strip() for c in m.group(2).split(",")])
        text = re.sub(r"\bINSERT\s+OR\s+REPLACE\s+INTO\b", "INSERT INTO", text, flags=re.I)
    ignore = bool(re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", text, re.I))
    text = re.sub(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", text, flags=re.I)
    text = re.sub(r"\bGROUP_CONCAT\s*\(\s*(DISTINCT\s+)?([^)]*?)\s*\)",
                  lambda g: f"string_agg({g.group(1) or ''}CAST({g.group(2)} AS text), ',')", text, flags=re.I)
    text = re.sub(r"\bIFNULL\s*\(", "COALESCE(", text, flags=re.I)
    text = re.sub(r"\bNOT\s+LIKE\b", "NOT ILIKE", text, flags=re.I)
    text = re.sub(r"(?<!NOT )\bLIKE\b", "ILIKE", text, flags=re.I)
    text = _greatest(text)
    # rejoin with the string literals back in place, then the date() modifiers (they contain literals)
    chunks = text.split("\x00")
    out = []
    for i, ch in enumerate(chunks):
        out.append(ch)
        if i < len(strings):
            out.append(strings[i])
    sql2 = "".join(out)
    sql2 = re.sub(r"\bdate\s*\(\s*([^,()]+?)\s*,\s*'([-+])\s*(\d+)\s+([a-z]+)'\s*\)", _date_mod, sql2, flags=re.I)
    sql2 = re.sub(r"\bdate\s*\(\s*'now'\s*\)", "CURRENT_DATE", sql2, flags=re.I)
    # ? -> %s outside literals (literals have no '?' rewrites; re-split to be exact)
    sql2 = "".join(p if s else p.replace("%", "%%").replace("?", "%s") for s, p in _split_strings(sql2))
    if ignore and not re.search(r"\bON\s+CONFLICT\b", sql2, re.I):
        sql2 = sql2.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    if replace_target:
        table, cols = replace_target
        pk = list(pk_of(table)) if pk_of else []
        if not pk:
            raise UnsupportedSQL(f"INSERT OR REPLACE into {table}: primary key unknown")
        sets = ", ".join(f"{c}=EXCLUDED.{c}" for c in cols if c not in pk)
        sql2 = sql2.rstrip().rstrip(";") + f" ON CONFLICT ({', '.join(pk)}) " + (f"DO UPDATE SET {sets}" if sets
                                                                                else "DO NOTHING")
    return sql2


def ddl(stmt: str) -> str:
    s = stmt
    s = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY\s+AUTOINCREMENT\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
               s, flags=re.I)
    s = re.sub(r"\bAUTOINCREMENT\b", "", s, flags=re.I)
    s = re.sub(r"\bREAL\b", "DOUBLE PRECISION", s, flags=re.I)
    s = re.sub(r"\bBLOB\b", "BYTEA", s, flags=re.I)
    s = re.sub(r"\bINTEGER\b", "BIGINT", s, flags=re.I)
    s = re.sub(r"\bDATETIME\b", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"CHECK\s*\(\s*id\s*=\s*1\s*\)", "CHECK (id = 1)", s, flags=re.I)
    return s


# ── a sqlite3-shaped connection over psycopg 3 ────────────────────────────
class Row(tuple):
    """Index and name access, like sqlite3.Row."""
    def __new__(cls, values, names):
        r = super().__new__(cls, values)
        r._names = names
        return r

    def __getitem__(self, k):
        if isinstance(k, str):
            return super().__getitem__(self._names.index(k))
        return super().__getitem__(k)

    def keys(self):
        return list(self._names)


class _Cursor:
    def __init__(self, cur):
        self._c = cur

    def _wrap(self, r):
        if r is None:
            return None
        names = [d.name for d in self._c.description] if self._c.description else []
        return Row(r, names)

    def fetchone(self):
        return self._wrap(self._c.fetchone())

    def fetchall(self):
        return [self._wrap(r) for r in self._c.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())

    @property
    def rowcount(self):
        return self._c.rowcount

    @property
    def description(self):
        return self._c.description


class PgConnection:
    def __init__(self, dsn: str):
        try:
            import psycopg
        except ImportError as e:
            raise RuntimeError('PostgreSQL backend needs: pip install "psycopg[binary]"') from e
        self._conn = psycopg.connect(dsn)
        self._pk = {}
        self.row_factory = None                                     # accepted for sqlite3 compatibility

    def pk_of(self, table):
        if table not in self._pk:
            cur = self._conn.execute(
                "SELECT a.attname FROM pg_index i JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey) "
                "WHERE i.indrelid=%s::regclass AND i.indisprimary", (table,))
            self._pk[table] = [r[0] for r in cur.fetchall()]
        return self._pk[table]

    def execute(self, sql, params=()):
        return _Cursor(self._conn.execute(translate(sql, self.pk_of), tuple(params or ())))

    def executemany(self, sql, seq):
        cur = self._conn.cursor()
        cur.executemany(translate(sql, self.pk_of), [tuple(p) for p in seq])
        return _Cursor(cur)

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()
