"""
PostgreSQL support (W38: DBS-05) -- the server database ATIP is moving to.

DATABASE PLAN (2026-10-09): PostgreSQL is the database for the hosted deployment, replacing the
earlier MySQL plan (db/mysql.py is legacy). SQLite remains the default for a local install.

  translate(sql)        SQLite -> PostgreSQL for the dialect ATIP actually uses (measured with
                        db/dialect_scan.py): ? placeholders, INSERT OR IGNORE, INSERT OR REPLACE (as an
                        upsert on the table's primary key), excluded., date(x, '+/-N unit'), GROUP_CONCAT,
                        2-argument MAX / MIN (-> GREATEST / LEAST), LIKE (case-insensitive in SQLite ->
                        ILIKE). PRAGMA and sqlite_master ARE translated, onto information_schema and a
                        catalogue subquery, so the existence checks db/schema.py's migrations rely on work.
                        rowid on an entry-order table becomes its `seq` column (db.backend.ENTRY_ORDER_TABLES).
                        Constructs with no safe automatic translation -- any other rowid, strftime() in SQL --
                        raise UnsupportedSQL naming the construct, so a missed query fails loudly instead of
                        returning something different.
  ddl(sqlite_create)    a CREATE TABLE / INDEX statement in PostgreSQL types (INTEGER PRIMARY KEY
                        AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY, REAL -> DOUBLE PRECISION,
                        BLOB -> BYTEA), plus the identity `seq` column on the entry-order tables
  PgConnection          a sqlite3-shaped connection over psycopg 3 (execute / executemany / cursor /
                        fetchone / fetchall / lastrowid / commit / rollback / close, and `with conn:`; rows
                        readable by index AND by column name, like sqlite3.Row), translating every statement on
                        the way through -- and raising the sqlite3 exception classes callers catch rather than
                        psycopg's, which are unrelated to them. See as_sqlite_error(). The session time zone is
                        pinned to UTC, which is what SQLite's CURRENT_TIMESTAMP / date('now') mean.

Activation (db/schema.pg_runtime_url): ATIP_DATABASE_URL=postgresql://user:pass@host:5432/atip plus
config.json "database": {"backend": "postgresql", "allow_experimental": true}. Both are required.
Requires `pip install "psycopg[binary]"` (in requirements.txt).
"""

from __future__ import annotations

import contextlib
import re
import sqlite3


class UnsupportedSQL(ValueError):
    pass


_UNSUPPORTED = [(re.compile(r"^\s*PRAGMA\b", re.I), "PRAGMA"), (re.compile(r"\bsqlite_master\b", re.I), "sqlite_master"),
                (re.compile(r"\browid\b", re.I), "rowid"), (re.compile(r"\bstrftime\s*\(", re.I), "strftime()")]

# sqlite_master as PostgreSQL sees it (type, name, tbl_name, sql) -- catalog queries run unchanged
_SQLITE_MASTER = (
    "(SELECT 'table' AS type, table_name AS name, table_name AS tbl_name, CAST(NULL AS text) AS sql "
    "FROM information_schema.tables WHERE table_schema=current_schema() AND table_type='BASE TABLE' "
    "UNION ALL SELECT 'view', table_name, table_name, view_definition FROM information_schema.views "
    "WHERE table_schema=current_schema() "
    "UNION ALL SELECT 'index', indexname, tablename, indexdef FROM pg_indexes WHERE schemaname=current_schema() "
    "UNION ALL SELECT DISTINCT 'trigger', trigger_name, event_object_table, CAST(NULL AS text) "
    "FROM information_schema.triggers WHERE trigger_schema=current_schema()) AS sqlite_master_pg")


def _table_info(t):
    pk = ("SELECT kcu.column_name FROM information_schema.table_constraints tc JOIN information_schema.key_column_usage "
          "kcu ON tc.constraint_name=kcu.constraint_name AND tc.table_schema=kcu.table_schema WHERE "
          f"tc.table_schema=current_schema() AND tc.table_name='{t}' AND tc.constraint_type='PRIMARY KEY'")
    return ("SELECT ordinal_position-1 AS cid, column_name AS name, upper(data_type) AS type, "
            "CASE WHEN is_nullable='NO' THEN 1 ELSE 0 END AS notnull, column_default AS dflt_value, "
            f"CASE WHEN column_name IN ({pk}) THEN 1 ELSE 0 END AS pk FROM information_schema.columns "
            f"WHERE table_schema=current_schema() AND table_name='{t}' ORDER BY ordinal_position")


_QUERY_ONLY_RX = re.compile(r"\s*PRAGMA\s+query_only\s*=\s*(\w+)\s*;?\s*$", re.I)


def _catalog(sql):
    """PRAGMAs ATIP uses -> PostgreSQL equivalents (or harmless no-ops); None if not one of them."""
    m = re.match(r"\s*PRAGMA\s+table_info\s*\(\s*[\"']?(\w+)[\"']?\s*\)\s*;?\s*$", sql, re.I)
    if m:
        return _table_info(m.group(1))
    m = _QUERY_ONLY_RX.match(sql)
    if m:                                     # PgConnection applies it to the current transaction too
        mode = "READ ONLY" if m.group(1).upper() in ("ON", "1", "TRUE", "YES") else "READ WRITE"
        return f"SET SESSION CHARACTERISTICS AS TRANSACTION {mode}"
    if re.match(r"\s*PRAGMA\s+(busy_timeout|foreign_keys|synchronous|cache_size)\b", sql, re.I):
        return "SELECT 1"
    if re.match(r"\s*PRAGMA\s+journal_mode\b", sql, re.I):
        return "SELECT 'wal' AS journal_mode"
    if re.match(r"\s*PRAGMA\s+(integrity_check|quick_check)\s*;?\s*$", sql, re.I):
        return "SELECT 'ok' AS integrity_check"
    return None


def _bool_aggs(sql):
    """SUM / AVG / TOTAL of a comparison (SQLite booleans are 0/1) -> SUM(CAST((cmp) AS INT))."""
    out, i = [], 0
    pat = re.compile(r"\b(SUM|AVG|TOTAL)\s*\(", re.I)
    cmp_rx = re.compile(r"\bIS\s+(NOT\s+)?NULL\b|<>|!=|<=|>=|[<>=]|\bLIKE\b|\bIN\b", re.I)
    while True:
        m = pat.search(sql, i)
        if not m:
            out.append(sql[i:])
            return "".join(out)
        depth, j = 1, m.end()
        while j < len(sql) and depth:
            depth += sql[j] == "("
            depth -= sql[j] == ")"
            j += 1
        arg = sql[m.end():j - 1]
        flat = arg                                            # only top-level comparisons count
        while re.search(r"\([^()]*\)", flat):
            flat = re.sub(r"\([^()]*\)", "", flat)
        out.append(sql[i:m.start()])
        if cmp_rx.search(flat) and not re.match(r"\s*(CASE|DISTINCT)\b", arg, re.I):
            fn = "SUM" if m.group(1).upper() == "TOTAL" else m.group(1)
            out.append(f"{fn}(CAST(({_bool_aggs(arg)}) AS INT))")
        else:
            out.append(m.group(0) + _bool_aggs(arg) + ")")
        i = j
_UNITS = {"day": "day", "days": "day", "month": "month", "months": "month", "year": "year", "years": "year",
          "hour": "hour", "hours": "hour", "minute": "minute", "minutes": "minute"}


def _split_strings(sql):
    """[(is_string_literal, text)] so rewrites never touch quoted text."""
    out, i, buf = [], 0, []
    while i < len(sql):
        ch = sql[i]
        if ch == "'":
            if buf:
                out.append((False, "".join(buf)))
                buf = []
            j = i + 1
            while j < len(sql):
                if sql[j] == "'" and (j + 1 >= len(sql) or sql[j + 1] != "'"):
                    break
                j += 2 if sql[j] == "'" else 1
            out.append((True, sql[i:j + 1]))
            i = j + 1
            continue
        buf.append(ch)
        i += 1
    if buf:
        out.append((False, "".join(buf)))
    return out


def _date_mod(m):
    arg, sign, n, unit = m.group(1).strip(), m.group(2), m.group(3), m.group(4).lower()
    u = _UNITS.get(unit)
    if not u:
        raise UnsupportedSQL(f"date modifier unit {unit!r}")
    base = "CURRENT_DATE" if arg.lower() in ("'now'",) else f"CAST({arg} AS date)"
    return f"CAST({base} {sign} INTERVAL '{n} {u}' AS date)"


def _greatest(sql):
    """MAX(a, b) / MIN(a, b) with a top-level comma -> GREATEST / LEAST (aggregates untouched)."""
    out, i = [], 0
    pat = re.compile(r"\b(MAX|MIN)\s*\(", re.I)
    while True:
        m = pat.search(sql, i)
        if not m:
            out.append(sql[i:])
            return "".join(out)
        depth, j, comma = 1, m.end(), False
        while j < len(sql) and depth:
            c = sql[j]
            if c == "(":
                depth += 1
            elif c == ")":
                depth -= 1
            elif c == "," and depth == 1:
                comma = True
            j += 1
        out.append(sql[i:m.start()])
        out.append(("GREATEST(" if m.group(1).upper() == "MAX" else "LEAST(") if comma else m.group(0))
        i = m.end()


def _qualify_upsert(sql, table, cols):
    """In ON CONFLICT ... DO UPDATE SET a=a+excluded.a, a bare `a` on the right is ambiguous in
    PostgreSQL (target row or excluded row?); SQLite means the target row -> `table.a`.

    `cols` arrives after backticks have become double quotes, so a reserved column
    reads as "rows" here. The name is matched with a non-word lookahead rather than
    \b, which cannot match after a closing quote -- it left "rows" unqualified and
    PostgreSQL answered: column reference "rows" is ambiguous.
    """
    m = re.search(r"\bDO\s+UPDATE\s+SET\b", sql, re.I)
    if not m or not cols:
        return sql
    head, tail = sql[:m.end()], sql[m.end():]
    names = "|".join(re.escape(c) for c in sorted(cols, key=len, reverse=True))
    out, depth, start, parts = [], 0, 0, []
    for i, ch in enumerate(tail):                     # split assignments on top-level commas
        depth += ch == "("
        depth -= ch == ")"
        if ch == "," and depth == 0:
            parts.append(tail[start:i])
            start = i + 1
    parts.append(tail[start:])
    for p in parts:
        if "=" in p:
            lhs, rhs = p.split("=", 1)
            rhs = re.sub(rf"(?<![\w.])({names})(?!\w)(?!\s*\()", rf"{table}.\1", rhs)
            p = lhs + "=" + rhs
        out.append(p)
    return head + ",".join(out)


def translate(sql: str, pk_of=None) -> str:
    """SQLite SQL -> PostgreSQL. pk_of(table) -> [[key columns], ...] (primary key and UNIQUE
    constraints) is needed for INSERT OR REPLACE: SQLite replaces on ANY unique key, so the key used
    is the first one the inserted columns cover (a surrogate id that is not inserted cannot clash)."""
    cat = _catalog(sql)
    if cat is not None:
        return cat
    if re.search(r"\bsqlite_master\b", sql, re.I):            # code parts only, never inside a literal
        sql = "".join(p if s else re.sub(r"\bsqlite_master\b", _SQLITE_MASTER, p, flags=re.I)
                      for s, p in _split_strings(sql))
    # rowid on an entry-order table (db.backend.ENTRY_ORDER_TABLES) -> its identity `seq` column, which
    # ddl() adds and which numbers rows in the order they were written: exactly what SQLite's rowid is
    # on those tables. Only for a statement that touches that one table, so `rowid` can never be read
    # against a different table in a join.
    if re.search(r"\browid\b", sql, re.I):
        from db.backend import ENTRY_ORDER_COLUMN, ENTRY_ORDER_TABLES
        code = " ".join(p for st, p in _split_strings(sql) if not st)
        tables = {t.lower() for t in re.findall(r"\b(?:FROM|JOIN|UPDATE|INTO)\s+([A-Za-z_]\w*)", code, re.I)}
        if len(tables) == 1 and tables <= ENTRY_ORDER_TABLES:
            sql = "".join(p if st else re.sub(r"\b((?:\w+\.)?)rowid\b", rf"\1{ENTRY_ORDER_COLUMN}", p, flags=re.I)
                          for st, p in _split_strings(sql))
    # rowid as an ORDER BY tie-breaker (entry order) -> ctid. Valid because every such use is on an
    # append-only table (perf_ledger, ml_dl_benefit: no UPDATE / DELETE, so tuples never move); any
    # other rowid use still fails below.
    ob = re.search(r"\bORDER\s+BY\b(?!.*\bORDER\s+BY\b)", sql, re.I | re.S)
    if ob and re.search(r"\browid\b", sql[ob.end():], re.I) and not re.search(r"\browid\b", sql[:ob.start()], re.I):
        sql = sql[:ob.end()] + re.sub(r"\b((?:\w+\.)?)rowid\b", r"\1ctid", sql[ob.end():], flags=re.I)
    for rx, name in _UNSUPPORTED:
        if rx.search("".join(p for s, p in _split_strings(sql) if not s)):
            raise UnsupportedSQL(f"{name} has no automatic PostgreSQL translation: {sql.strip()[:120]}")
    # Backtick-quoted identifiers. ATIP's shared SQL quotes the columns that are
    # reserved words in MySQL 8 (signal, key, rank, rows, change, trigger); SQLite
    # accepts backticks for MySQL compatibility, PostgreSQL does not, so they become
    # the standard double quote here. Double quoting also makes the name
    # case-sensitive in PostgreSQL -- harmless, as ATIP declares every column in
    # lower case, which is what an unquoted name folds to.
    sql = "".join(p if s else p.replace("`", '"') for s, p in _split_strings(sql))

    parts = _split_strings(sql)
    text = "\x00".join(p for s, p in parts if not s)                    # code only, joined by markers
    strings = [p for s, p in parts if s]
    replace_target = None
    m = re.search(r"\bINSERT\s+OR\s+REPLACE\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)", text, re.I)
    if m:
        replace_target = (m.group(1), [c.strip() for c in m.group(2).split(",")])
        text = re.sub(r"\bINSERT\s+OR\s+REPLACE\s+INTO\b", "INSERT INTO", text, flags=re.I)
    ignore = bool(re.search(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", text, re.I))
    text = re.sub(r"\bINSERT\s+OR\s+IGNORE\s+INTO\b", "INSERT INTO", text, flags=re.I)
    text = re.sub(r"\bGROUP_CONCAT\s*\(\s*(DISTINCT\s+)?([^)]*?)\s*\)",
                  lambda g: f"string_agg({g.group(1) or ''}CAST({g.group(2)} AS text), ',')", text, flags=re.I)
    text = re.sub(r"\bIFNULL\s*\(", "COALESCE(", text, flags=re.I)
    text = re.sub(r"\bNOT\s+LIKE\b", "NOT ILIKE", text, flags=re.I)
    text = re.sub(r"(?<!NOT )\bLIKE\b", "ILIKE", text, flags=re.I)
    text = _greatest(text)
    text = _bool_aggs(text)
    # rejoin with the string literals back in place, then the date() modifiers (they contain literals)
    chunks = text.split("\x00")
    out = []
    for i, ch in enumerate(chunks):
        out.append(ch)
        if i < len(strings):
            out.append(strings[i])
    sql2 = "".join(out)
    sql2 = re.sub(r"\bdate\s*\(\s*([^,()]+?)\s*,\s*'([-+])\s*(\d+)\s+([a-z]+)'\s*\)", _date_mod, sql2, flags=re.I)
    sql2 = re.sub(r"\bdate\s*\(\s*'now'\s*\)", "CURRENT_DATE", sql2, flags=re.I)
    # ? -> %s outside literals; every % is doubled, INSIDE literals too (LIKE 'a%'): psycopg parses the
    # whole statement for placeholders when parameters are passed, and PgConnection always passes them
    sql2 = "".join(p.replace("%", "%%") if s else p.replace("%", "%%").replace("?", "%s")
                   for s, p in _split_strings(sql2))
    if ignore and not re.search(r"\bON\s+CONFLICT\b", sql2, re.I):
        sql2 = sql2.rstrip().rstrip(";") + " ON CONFLICT DO NOTHING"
    if replace_target:
        table, cols = replace_target
        keys = [list(k) for k in (pk_of(table) if pk_of else []) if k]
        if keys and isinstance(keys[0], str):                 # a bare [col, ...] list = one key
            keys = [keys]
        key = next((k for k in keys if set(k) <= set(cols)), None)
        if not key:
            raise UnsupportedSQL(f"INSERT OR REPLACE into {table}: no primary / unique key among the inserted "
                                 f"columns {cols}")
        sets = ", ".join(f"{c}=EXCLUDED.{c}" for c in cols if c not in key)
        sql2 = sql2.rstrip().rstrip(";") + f" ON CONFLICT ({', '.join(key)}) " + (f"DO UPDATE SET {sets}" if sets
                                                                                  else "DO NOTHING")
    else:
        m2 = re.search(r"\bINSERT\s+INTO\s+([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)", sql2, re.I)
        if m2:
            sql2 = _qualify_upsert(sql2, m2.group(1), [c.strip() for c in m2.group(2).split(",")])
    return sql2


def ddl(stmt: str) -> str:
    s = stmt
    # INTEGER PRIMARY KEY is the rowid alias in SQLite: auto-numbered with or without AUTOINCREMENT
    s = re.sub(r"\bINTEGER\s+PRIMARY\s+KEY(\s+AUTOINCREMENT)?\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
               s, flags=re.I)
    s = re.sub(r"\bAUTOINCREMENT\b", "", s, flags=re.I)
    s = re.sub(r"\(\s*datetime\s*\(\s*'now'\s*\)\s*\)|\bdatetime\s*\(\s*'now'\s*\)", "CURRENT_TIMESTAMP", s, flags=re.I)
    s = re.sub(r"\(\s*date\s*\(\s*'now'\s*\)\s*\)|\bdate\s*\(\s*'now'\s*\)", "CURRENT_DATE", s, flags=re.I)
    s = re.sub(r"\bWITHOUT\s+ROWID\b", "", s, flags=re.I)
    s = re.sub(r"\s+COLLATE\s+NOCASE\b", "", s, flags=re.I)
    s = re.sub(r"\bREAL\b", "DOUBLE PRECISION", s, flags=re.I)
    s = re.sub(r"\bBLOB\b", "BYTEA", s, flags=re.I)
    s = re.sub(r"\bINTEGER\b", "BIGINT", s, flags=re.I)
    s = re.sub(r"\bBOOL(EAN)?\b", "SMALLINT", s, flags=re.I)     # SQLite stores 0/1 and the code compares with 1
    s = re.sub(r"\bDATETIME\b", "TIMESTAMP", s, flags=re.I)
    s = re.sub(r"CHECK\s*\(\s*id\s*=\s*1\s*\)", "CHECK (id = 1)", s, flags=re.I)
    m = re.match(r"\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?\"?([A-Za-z_]\w*)\"?\s*\((.*)\)\s*;?\s*$", s, re.I | re.S)
    if m:
        from db.backend import ENTRY_ORDER_COLUMN, ENTRY_ORDER_TABLES
        if m.group(1).lower() in ENTRY_ORDER_TABLES and not re.search(
                rf"(?:\(|,)\s*\"?{ENTRY_ORDER_COLUMN}\"?\s", m.group(2), re.I):
            s = s[:m.end(2)] + f",\n  {ENTRY_ORDER_IDENTITY}" + s[m.end(2):]
    return s


# The entry-order column (db.backend.ENTRY_ORDER_TABLES). BY DEFAULT rather than ALWAYS so a bulk
# copy can carry numbers over; UNIQUE because it is an order, and two rows never share a place in it.
ENTRY_ORDER_IDENTITY = "seq BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE"


APPEND_ONLY_FN = ("CREATE OR REPLACE FUNCTION atip_append_only() RETURNS trigger LANGUAGE plpgsql AS $$ "
                  "BEGIN RAISE EXCEPTION '%', TG_ARGV[0]; END $$")


def trigger_ddl(sql: str) -> str:
    """ATIP's SQLite triggers are all append-only guards:
         BEFORE UPDATE|DELETE ON t [WHEN cond] BEGIN SELECT RAISE(ABORT, 'msg'); END
    -> a PostgreSQL row trigger calling atip_append_only('msg') (APPEND_ONLY_FN, created first).
    Anything else raises UnsupportedSQL rather than being dropped silently."""
    m = re.match(r"\s*CREATE\s+TRIGGER\s+(IF\s+NOT\s+EXISTS\s+)?(\w+)\s+(BEFORE|AFTER)\s+(UPDATE|DELETE|INSERT)\s+"
                 r"ON\s+(\w+)\s+(?:FOR\s+EACH\s+ROW\s+)?(?:WHEN\s+(.+?)\s+)?BEGIN\s+SELECT\s+RAISE\s*\(\s*ABORT\s*,\s*"
                 r"'((?:[^']|'')*)'\s*\)\s*;\s*END\s*;?\s*$", sql, re.I | re.S)
    if not m:
        raise UnsupportedSQL(f"trigger is not an append-only guard: {' '.join(sql.split())[:120]}")
    if_not_exists, name, when, event, table, cond, msg = m.groups()
    cond_sql = f" WHEN ({cond})" if cond else ""
    # PostgreSQL has no CREATE TRIGGER IF NOT EXISTS; OR REPLACE (PG 14+) is the idempotent form, and
    # replacing a guard with the identical guard changes nothing. Without it ops/migrations.py's
    # IF NOT EXISTS triggers fail the second time they meet a table that already has them.
    verb = "CREATE OR REPLACE TRIGGER" if if_not_exists else "CREATE TRIGGER"
    return (f"{verb} {name} {when.upper()} {event.upper()} ON {table} FOR EACH ROW{cond_sql} "
            f"EXECUTE FUNCTION atip_append_only('{msg}')")


def keys_from_ddl(stmts) -> dict:
    """{table: [[key columns], ...]} from CREATE TABLE / CREATE UNIQUE INDEX statements (PK first)."""
    keys: dict = {}
    for s in stmts:
        m = re.search(r"CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z_]\w*)\s*\((.*)\)", s, re.I | re.S)
        if m:
            t, body = m.group(1), m.group(2)
            ks = keys.setdefault(t, [])
            for c in re.finditer(r"PRIMARY\s+KEY\s*\(([^)]*)\)", body, re.I):
                ks.insert(0, [x.strip() for x in c.group(1).split(",")])
            for c in re.finditer(r"(?:^|,)\s*([A-Za-z_]\w*)\s+[^,]*?\bPRIMARY\s+KEY\b", body, re.I):
                ks.insert(0, [c.group(1)])
            for c in re.finditer(r"\bUNIQUE\s*\(([^)]*)\)", body, re.I):
                ks.append([x.strip() for x in c.group(1).split(",")])
            for c in re.finditer(r"(?:^|,)\s*([A-Za-z_]\w*)\s+\w+[^,(]*?\bUNIQUE\b(?!\s*\()", body, re.I):
                ks.append([c.group(1)])
            continue
        m = re.search(r"CREATE\s+UNIQUE\s+INDEX\s+(?:IF\s+NOT\s+EXISTS\s+)?\w+\s+ON\s+([A-Za-z_]\w*)\s*\(([^)]*)\)",
                      s, re.I)
        if m:
            keys.setdefault(m.group(1), []).append([x.strip().split()[0] for x in m.group(2).split(",")])
    return keys


# ── a sqlite3-shaped connection over psycopg 3 ────────────────────────────
class Row(tuple):
    """Index and name access, like sqlite3.Row."""
    def __new__(cls, values, names):
        r = super().__new__(cls, values)
        r._names = names
        return r

    def __getitem__(self, k):
        if isinstance(k, str):
            return super().__getitem__(self._names.index(k))
        return super().__getitem__(k)

    def keys(self):
        return list(self._names)


# ── errors: psycopg's exceptions as the sqlite3 ones callers catch ─────────
#
# Same problem, and the same remedy, as db/mysql.py's as_sqlite_error() -- see the
# note there. psycopg and sqlite3 both implement PEP 249, but their hierarchies are
# unrelated, so `except sqlite3.OperationalError` catches nothing psycopg raises.
# ATIP's additive migrations are built on that clause (db/schema.py swallows
# "column already exists" to make ALTER TABLE ADD COLUMN idempotent), so the
# connection has to raise what they catch, exactly as it already answers to `?`
# placeholders and sqlite3.Row.
#
# The rule here is simpler than MySQL's errno list, because PostgreSQL reports the
# SQL standard's own SQLSTATE and class 23 *is* "integrity constraint violation":
# 23502 not-null, 23503 foreign key, 23505 unique, 23514 check, 23001 restrict,
# 23P01 exclusion. That is exactly the set SQLite raises IntegrityError for, so the
# prefix is the mapping -- no table of codes to fall out of date.
#
# psycopg's own classes cannot be used for this. They are finer-grained than
# sqlite3's (DuplicateColumn, UndefinedTable, SyntaxError) and they sort conditions
# differently again: a duplicate column is DuplicateColumn where SQLite says
# OperationalError, and a CHECK violation is CheckViolation where PyMySQL -- the
# other backend -- says OperationalError. Verified against PostgreSQL 16.14.


def as_sqlite_error(exc: Exception) -> Exception:
    """`exc` as the sqlite3 class SQLite would raise for the same condition.

    `args` is carried over unchanged, so the message reads the way psycopg wrote it
    -- and unlike PyMySQL, psycopg puts the message in args[0], which is also
    sqlite3's own convention. The SQLSTATE is kept on the result as `.sqlstate` for
    anything that wants to switch on it. Whatever is not a psycopg error is returned
    untouched, which is what keeps UnsupportedSQL and ordinary programming mistakes
    from being disguised as database trouble.
    """
    try:
        import psycopg
    except ImportError:                       # pragma: no cover - PgConnection cannot exist
        return exc
    if not isinstance(exc, psycopg.Error):
        return exc
    sqlstate = getattr(exc, "sqlstate", None) or ""
    cls = sqlite3.IntegrityError if sqlstate.startswith("23") else sqlite3.OperationalError
    out = cls(*exc.args).with_traceback(exc.__traceback__)
    out.sqlstate = sqlstate or None
    return out


@contextlib.contextmanager
def sqlite_errors():
    """Re-raise whatever psycopg raises inside as the sqlite3 class SQLite would."""
    try:
        yield
    except Exception as e:
        translated = as_sqlite_error(e)
        if translated is e:
            raise
        raise translated from e


class _Cursor:
    def __init__(self, cur, conn=None):
        self._c = cur
        self._conn = conn                            # the psycopg connection, for lastrowid

    def _wrap(self, r):
        if r is None:
            return None
        names = [d.name for d in self._c.description] if self._c.description else []
        return Row(r, names)

    def fetchone(self):
        with sqlite_errors():
            return self._wrap(self._c.fetchone())

    def fetchall(self):
        with sqlite_errors():
            return [self._wrap(r) for r in self._c.fetchall()]

    def __iter__(self):
        return iter(self.fetchall())

    @property
    def rowcount(self):
        return self._c.rowcount

    @property
    def lastrowid(self):
        """sqlite3's cursor.lastrowid: the id the last INSERT generated.

        PostgreSQL has no rowid; an INSERT into an identity column draws from a sequence,
        and lastval() is the session's most recent sequence value -- the same number. Read
        inside a nested transaction (a savepoint), because lastval() raises when the
        session has drawn none yet, and an error would otherwise abort the caller's
        transaction. Callers are enterprise/notifications.py and alerts/telegram.py, which
        read it straight after their INSERT."""
        if self._conn is None:
            return None
        try:
            with self._conn.transaction():
                r = self._conn.execute("SELECT lastval()").fetchone()
            return r[0] if r else None
        except Exception:
            return None

    @property
    def description(self):
        return self._c.description


class _NullCursor:
    """What a statement that sends nothing returns (BEGIN, a DROP TRIGGER IF EXISTS of a trigger
    that is not there): sqlite3 returns a cursor for those too, with no rows."""
    description = None
    rowcount = -1
    lastrowid = None

    def fetchone(self):
        return None

    def fetchall(self):
        return []

    def __iter__(self):
        return iter(())


_TXN_RX = re.compile(r"\s*(BEGIN|COMMIT|END|ROLLBACK)(?:\s+(DEFERRED|IMMEDIATE|EXCLUSIVE))?(?:\s+TRANSACTION)?\s*;?\s*$",
                     re.I)


def _session_options(dsn: str) -> dict:
    """psycopg.connect() keyword arguments that pin the session time zone to UTC.

    A TIMESTAMP column's DEFAULT CURRENT_TIMESTAMP, CURRENT_DATE and now() are all read in
    the SESSION time zone, which otherwise comes from the server's configuration -- UTC in
    the postgres Docker image, but the OS zone (Asia/Kolkata) on a VPS installed from
    packages. ATIP's SQLite defaults (CURRENT_TIMESTAMP, date('now')) are UTC, so a server
    left on IST would stamp every defaulted row 5h30m away from the same row on SQLite and
    from rows copied over by tools/sqlite_to_postgres.py. This is the PostgreSQL side of the
    fix db/mysql.py made for MySQL's TIMESTAMP columns. Explicitly written values are
    TIMESTAMP WITHOUT TIME ZONE and are stored as given either way.

    Any `options` already in the DSN are kept; the time zone is appended to them.
    """
    try:
        from psycopg.conninfo import conninfo_to_dict
        existing = conninfo_to_dict(dsn).get("options") or ""
    except Exception:
        existing = ""
    return {"options": f"{existing} -c TimeZone=UTC".strip()}


class PgConnection:
    def __init__(self, dsn: str):
        try:
            import psycopg
        except ImportError as e:
            raise RuntimeError('PostgreSQL backend needs: pip install "psycopg[binary]"') from e
        self._conn = psycopg.connect(dsn, **_session_options(dsn))
        self._pk = {}
        self._fn_ready = False                                      # atip_append_only() created this session
        self._dirty = False                                         # this transaction has written (see _send)
        self.row_factory = None                                     # accepted for sqlite3 compatibility

    def pk_of(self, table):
        """[[columns] per unique index], primary key first."""
        if table in self._pk:
            return self._pk[table]
        cur = self._send(
            "SELECT i.indexrelid, i.indisprimary, a.attname FROM pg_index i "
            "JOIN pg_attribute a ON a.attrelid=i.indrelid AND a.attnum=ANY(i.indkey) "
            "WHERE i.indrelid=%s::regclass AND i.indisunique ORDER BY i.indisprimary DESC, i.indexrelid",
            (table,))
        keys: dict = {}
        for idx, _prim, col in cur.fetchall():
            keys.setdefault(idx, []).append(col)
        self._pk[table] = list(keys.values())
        return self._pk[table]

    @staticmethod
    def _is_ddl(sql):
        return sql.lstrip().upper().startswith(("CREATE ", "ALTER ", "DROP "))

    def execute(self, sql, params=()):
        # Translation happens outside sqlite_errors(): it touches no server, so a
        # statement this backend cannot express raises UnsupportedSQL rather than
        # arriving disguised as a database error.
        m = _TXN_RX.match(sql)
        if m:
            return self._transaction_control(m)
        m = _QUERY_ONLY_RX.match(sql)
        if m:
            return self._query_only(m.group(1).upper() in ("ON", "1", "TRUE", "YES"))
        if self._is_ddl(sql):                       # untouched by placeholder parsing (trigger bodies use %)
            if re.match(r"\s*CREATE\s+(OR\s+REPLACE\s+)?TRIGGER", sql, re.I):
                stmt = sql if re.search(r"\bEXECUTE\s+FUNCTION\b", sql, re.I) else trigger_ddl(sql)
                self._ensure_append_only_fn()
            elif re.match(r"\s*CREATE\s+(OR\s+REPLACE\s+)?FUNCTION", sql, re.I):
                stmt = sql                          # PostgreSQL already (atip_append_only)
            elif re.match(r"\s*DROP\s+TRIGGER\b", sql, re.I):
                stmt = self._drop_trigger(sql)
                if stmt is None:                    # IF EXISTS, and it does not
                    return _NullCursor()
            else:
                stmt = ddl(sql)
            cur = self._send(stmt)
            self._upgrade_entry_order(stmt)
            return cur
        return self._send(translate(sql, self.pk_of), tuple(params or ()))

    def _send(self, stmt, params=None, many=False):
        """Send one statement with SQLite's failure semantics.

        In SQLite a failed statement fails alone: the transaction around it carries on,
        and ATIP leans on that everywhere it probes ("try the query, fall back if the
        table is not there yet" -- portfolio/live_pnl.py, the additive migrations). In
        PostgreSQL the same failure aborts the whole transaction, and every later
        statement on the connection is refused until a rollback. So:

          * while the transaction has written nothing, a failure rolls it back -- that
            loses nothing and leaves the connection usable;
          * once it has written, each statement runs in a savepoint (psycopg's nested
            transaction()), so a failure undoes that statement and nothing else.

        Reads outside a write transaction cost nothing extra; the savepoint round trips
        are paid only inside write transactions."""
        writes = not re.match(r"\s*(SELECT|SHOW|VALUES)\b", stmt, re.I)
        with sqlite_errors():
            if self._dirty:
                with self._conn.transaction():
                    cur = self._exec(stmt, params, many)
            else:
                try:
                    cur = self._exec(stmt, params, many)
                except Exception:
                    self._conn.rollback()
                    raise
        self._dirty = self._dirty or writes
        return cur

    def _exec(self, stmt, params, many):
        if many:
            cur = self._conn.cursor()
            cur.executemany(stmt, params)
            return _Cursor(cur, self._conn)
        return _Cursor(self._conn.execute(stmt, params) if params is not None else self._conn.execute(stmt),
                       self._conn)

    def _transaction_control(self, m):
        """SQLite's transaction statements, which ops/jobs.py and ops/migrations.py send as SQL.

        BEGIN [DEFERRED]: psycopg opens a transaction before the first statement anyway
        (outside autocommit), which is all BEGIN asks for. BEGIN IMMEDIATE / EXCLUSIVE --
        a syntax error here -- means "take the write lock now": ops/jobs.acquire() relies
        on it to read a job's lock row and claim it with no other process in between. A
        transaction-scoped advisory lock gives the same guarantee: every IMMEDIATE section
        on the database queues behind the one holding it until that one commits or rolls
        back. COMMIT / END / ROLLBACK go through commit() / rollback(), so the bookkeeping
        _send() relies on is reset."""
        verb, mode = m.group(1).upper(), (m.group(2) or "").upper()
        if verb == "BEGIN":
            if mode in ("IMMEDIATE", "EXCLUSIVE"):
                cur = self._send("SELECT pg_advisory_xact_lock(hashtext('atip:begin_immediate'))")
                # Holding the lock counts as writing: a later failed statement must undo only
                # itself (a savepoint), not roll the transaction back and drop the lock while
                # the caller carries on as if it still held it.
                self._dirty = True
                return cur
            return _NullCursor()
        if verb in ("COMMIT", "END"):
            self.commit()
        else:
            self.rollback()
        return _NullCursor()

    def _query_only(self, on):
        """SQLite's PRAGMA query_only -> PostgreSQL read-only transactions, from this one on.

        tools/atip_mcp.py opens its connection with it, so the MCP tools cannot write;
        without this the PRAGMA failed to translate and the guarantee was quietly lost.
        psycopg starts the next transaction READ ONLY; a read-only transaction already
        open is rolled back first (it has nothing to lose), so the very next statement is
        covered. Changing it mid-write is refused rather than half-applied."""
        if self._dirty:
            raise sqlite3.OperationalError("cannot change query_only inside a write transaction")
        with sqlite_errors():
            self._conn.rollback()
            self._conn.read_only = bool(on)
        return _NullCursor()

    def _ensure_append_only_fn(self):
        """The function every append-only guard calls (trigger_ddl). Created on demand, so a
        database built by init_db() / ops.migrations -- not only one restored from the
        schema dump -- can take the guards. CREATE OR REPLACE makes it idempotent."""
        if not self._fn_ready:
            self._send(APPEND_ONLY_FN)
            self._fn_ready = True

    def _drop_trigger(self, sql):
        """SQLite's DROP TRIGGER [IF EXISTS] name -> PostgreSQL's, which also needs ON table.

        The table is read from the catalogue. None means IF EXISTS was given and the trigger
        does not exist, so there is nothing to send."""
        m = re.match(r"\s*DROP\s+TRIGGER\s+(IF\s+EXISTS\s+)?\"?(\w+)\"?(\s+ON\s+.+?)?\s*;?\s*$", sql, re.I | re.S)
        if not m or m.group(3):
            return sql
        if_exists, name = m.group(1), m.group(2)
        r = self._send("SELECT event_object_table FROM information_schema.triggers WHERE "
                       "trigger_schema=current_schema() AND trigger_name=%s LIMIT 1", (name,)).fetchone()
        if not r:
            if if_exists:
                return None
            raise sqlite3.OperationalError(f"no such trigger: {name}")
        return f"DROP TRIGGER {'IF EXISTS ' if if_exists else ''}{name} ON {r[0]}"

    def _upgrade_entry_order(self, stmt):
        """Give an entry-order table that predates its `seq` column one.

        ddl() puts the column into a NEW table; CREATE TABLE IF NOT EXISTS on a table made
        by an earlier release (the W38 migration path) changes nothing, so it is added here.
        PostgreSQL numbers the existing rows in physical order as it adds the identity, and
        both tables are append-only (ops/migrations.py 0005; ml_dl_benefit is only ever
        inserted into), so physical order is the order they were written."""
        m = re.match(r"\s*CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?\"?([A-Za-z_]\w*)\"?", stmt, re.I)
        if not m:
            return
        from db.backend import ENTRY_ORDER_TABLES
        if m.group(1).lower() in ENTRY_ORDER_TABLES:
            self._send(f"ALTER TABLE {m.group(1)} ADD COLUMN IF NOT EXISTS {ENTRY_ORDER_IDENTITY}")

    def executemany(self, sql, seq):
        return self._send(translate(sql, self.pk_of), [tuple(p) for p in seq], many=True)

    def reset_identity(self, table, column="id"):
        """After a bulk copy with explicit ids, move the identity sequence past MAX(id)."""
        self._send(f"SELECT setval(pg_get_serial_sequence('{table}', '{column}'), "
                   f"COALESCE((SELECT MAX({column}) FROM {table}), 0) + 1, false)")

    def commit(self):
        with sqlite_errors():
            self._conn.commit()
        self._dirty = False

    def rollback(self):
        with sqlite_errors():
            self._conn.rollback()
        self._dirty = False

    def close(self):
        self._conn.close()

    def cursor(self):
        """sqlite3 compatibility: a connection-level cursor that behaves like ours.

        init_db() is hundreds of `conn.cursor().execute(...)` calls, so without this
        the PostgreSQL backend could not create the schema at all -- it failed with
        AttributeError before any SQL was sent. MySQLConnection has had it; this is
        the sibling catching up.
        """
        return self

    def __enter__(self):
        return self

    def __exit__(self, *exc):
        if exc and exc[0]:
            self.rollback()
        else:
            self.commit()
        return False
