"""W15.5 tab: model / executable / actual / benchmark returns and their attribution."""

HTML = r"""
<div id="prf_msg"></div>
<div class="row"><select id="f_pf"></select><label class="muted">from <input id="f_start" type="date"></label><label class="muted">to <input id="f_end" type="date"></label>
<select id="f_bm"></select><input id="f_hz" type="number" placeholder="model horizon (20)" style="width:140px"><input id="f_slip" type="number" step="any" placeholder="slippage bps (10)" style="width:130px"><input id="f_strat" placeholder="strategy id (all)" style="width:130px" title="limit ACTUAL to one strategy's trades">
<button class="primary" onclick="prfRun(true)">Build &amp; save report</button><button onclick="prfRun(false)">Preview</button><button onclick="prfPreviewCsv()">Preview as CSV</button><button onclick="prfSync()">Import new transactions</button></div>
<p class="muted">Four returns, never one: MODEL (signals at the signal price), EXECUTABLE (as an account could have traded them), ACTUAL (your ledger), BENCHMARK (same dates, and your cash flows invested in it).</p>
<div id="prf_head"></div>
<h2>The four returns</h2><div id="prf_cmp"></div><div id="prf_gaps" class="muted"></div>
<h2>Actual portfolio</h2><div id="prf_act"></div>
<h2>Cost attribution</h2><div id="prf_cost"></div>
<h2>Contribution (portfolio attribution)</h2><div id="prf_contrib"></div>
<div class="adv"><h2>Risk contribution</h2><div id="prf_risk"></div></div>
<h2>Cash account</h2><div id="prf_acct" class="muted"></div>
<h2>Signal attribution</h2><div id="prf_sig"></div>
<div class="adv"><h2>Model &amp; executable trades</h2><div id="prf_trades" class="scroll"></div>
<h2>Audit</h2><div id="prf_audit" class="muted" style="font-size:11.5px;overflow-wrap:anywhere"></div></div>
<div class="adv"><h2>Ledger</h2>
<div class="row"><select id="x_pf"><option>MANUAL</option><option>LIVE</option></select><input id="x_date" type="date"><select id="x_kind"><option>BUY</option><option>SELL</option><option>OPENING</option><option>DIVIDEND</option><option>FEE</option><option>DEPOSIT</option><option>WITHDRAWAL</option></select>
<input id="x_sym" placeholder="symbol" style="width:110px"><input id="x_qty" type="number" step="any" placeholder="qty" style="width:80px"><input id="x_px" type="number" step="any" placeholder="price" style="width:90px"><input id="x_fees" type="number" step="any" placeholder="fees" style="width:80px"><input id="x_gross" type="number" step="any" placeholder="amount (dividend / fee / cash)" style="width:180px"><input id="x_sig" placeholder="signal id (optional)" style="width:140px"><button onclick="prfAddTxn()">Add transaction</button></div>
<div id="prf_ledger" class="scroll" style="margin-top:6px"></div></div>
<h2>Saved reports</h2><div id="prf_hist"></div>
"""

JS = r"""
let PRF=null;
function prfRender(r){PRF=r;const A=r.actual;
 document.getElementById('prf_head').innerHTML=`<div class="muted">${esc(r.portfolio)} · ${esc(r.period.start)} → ${esc(r.period.end)} (${r.period.sessions} sessions) · benchmark ${esc(r.benchmark)} ${r.strategy?'· strategy '+esc(r.strategy):''} ${r.report_id?'· saved '+esc(r.report_id)+` · <a style="color:var(--accent)" href="/api/wealth/performance/reports/${r.report_id}/export?format=csv">CSV</a> · <a style="color:var(--accent)" href="/api/wealth/performance/reports/${r.report_id}/export?format=json">JSON</a> · <a href="#" style="color:var(--accent)" onclick="prfVerify('${r.report_id}');return false">verify against today's data</a>`:'· preview (not saved)'}</div><div id="prf_verify" class="muted"></div>`;
 document.getElementById('prf_cmp').innerHTML=table(['Return','What it measures','#Total','#Days invested','#Annualized','#XIRR','#Volatility','#Sharpe','#Sortino','#Max DD','#Alpha','#Beta','#Trades','#Win rate'],r.comparison.map(c=>`<tr><td><b>${c.return}</b></td><td class="muted" style="font-size:11px">${esc(c.definition)}</td><td class="n ${c.total_return_pct<0?'bad':'good'}">${pct(c.total_return_pct,2)}</td><td class="n">${c.days_invested??'—'}</td><td class="n">${pct(c.annualized_pct,2)}</td><td class="n">${pct(c.xirr_pct,2)}</td><td class="n">${pct(c.volatility_pct,1)}</td><td class="n">${num(c.sharpe,2)}</td><td class="n">${num(c.sortino,2)}</td><td class="n">${pct(c.max_drawdown_pct,1)}</td><td class="n">${pct(c.alpha_annual_pct,1)}</td><td class="n">${num(c.beta,2)}</td><td class="n">${c.trades??'—'}</td><td class="n">${pct(c.win_rate_pct,1)}</td></tr>`));
 const G=r.gaps;document.getElementById('prf_gaps').innerHTML=`Model − executable ${num(G.model_minus_executable_pp,2)} pts · executable − actual ${num(G.executable_minus_actual_pp,2)} pts · actual − benchmark ${num(G.actual_minus_benchmark_pp,2)} pts. ${esc(G.note)}`;
 if(A.status!=='OK'){document.getElementById('prf_act').innerHTML=`<div class="msg">${esc(A.status)} ${esc(A.message||'no transactions in this portfolio')}</div>`;['prf_cost','prf_contrib','prf_risk','prf_acct'].forEach(i=>document.getElementById(i).innerHTML='')}
 else{const R=A.returns,T=A.trade_stats;
  document.getElementById('prf_act').innerHTML=`<div class="grid">${card('Time-weighted',pct(R.twr.total_return_pct,2),R.twr.annualized_note||('annualized '+pct(R.twr.annualized_pct,2)))}${card('XIRR (money-weighted)',pct(R.xirr_pct,2),R.xirr_note||'')}${card('Realized P&L (period)',inr(R.realized_pnl_period),'lifetime to end '+inr(R.realized_pnl)+' · average cost')}${card('Unrealized P&L',inr(R.unrealized_pnl),'vs cost basis')}${card('Gain in period',inr(R.gain),pct(R.return_on_avg_capital_pct,2)+' on average capital '+inr(R.average_invested_capital))}${card('Same flows in '+esc(R.pme.benchmark),R.pme.value_if_invested==null?'—':inr(R.pme.value_if_invested),R.pme.value_if_invested==null?esc(R.pme.note):'PME XIRR '+pct(R.pme.xirr_pct,2))}${card('Trades',T.trades??0,'win '+pct(T.win_rate_pct,1)+' · PF '+num(T.profit_factor,2)+' · hold '+num(T.avg_holding_days,1)+'d')}</div>`+
   table(['Symbol','#Qty','#Avg cost','#Cost basis','#Price','#Market value','#Unrealized','#Realized','#Fees','#Dividends'],A.positions.map(p=>`<tr><td>${esc(p.symbol)}</td><td class="n">${num(p.quantity,2)}</td><td class="n">${p.avg_cost==null?'—':num(p.avg_cost)}</td><td class="n">${inr(p.cost_basis)}</td><td class="n">${p.price==null?'—':num(p.price)}</td><td class="n">${inr(p.market_value)}</td><td class="n ${p.unrealized<0?'bad':'good'}">${inr(p.unrealized)}</td><td class="n ${p.realized<0?'bad':'good'}">${inr(p.realized)}</td><td class="n">${inr(p.fees)}</td><td class="n">${inr(p.dividends)}</td></tr>`))+
   (A.data_quality.length?'<h3>Data quality</h3>'+A.data_quality.slice(0,20).map(d=>`<div class="warn">${esc(d.issue)}: ${esc(typeof d.detail==='object'?JSON.stringify(d.detail):d.detail)}${d.symbol?' ('+esc(d.symbol)+')':''}</div>`).join(''):'');
  const K=A.costs;document.getElementById('prf_cost').innerHTML=`<div class="grid">${card('Fees',inr(K.fees_total),Object.entries(K.by_kind).filter(([k,v])=>v).map(([k,v])=>k+' '+inr(v)).join(' · '))}${card('Slippage vs reference',inr(K.slippage_vs_reference),K.trades_with_reference_price+' trade(s) with a reference price')}${card('Reconciled to ledger',K.reconciliation.ok?'<span class="good">yes</span>':'<span class="bad">NO</span>','difference '+inr(K.reconciliation.difference))}${card('Recorded components',K.components_cover_pct==null?'—':pct(K.components_cover_pct,0)+' of fees',Object.entries(K.components||{}).map(([k,v])=>k+' '+inr(v)).join(' · '))}${K.statutory_estimate?card('NSE charges (estimate)',inr(K.statutory_estimate.by_component.total),Object.entries(K.statutory_estimate.by_component).filter(([k])=>k!=='total').map(([k,v])=>k+' '+inr(v)).join(' · ')):''}</div>${K.statutory_estimate?'<div class="muted">'+esc(K.statutory_estimate.note)+'</div>':''}`;
  const RC=A.risk_contribution||{};document.getElementById('prf_risk').innerHTML=RC.status==='OK'?`<div class="muted">${esc(RC.method)} · portfolio volatility ${pct(RC.portfolio_vol_pct,2)} · reconciles: ${RC.reconciles?'yes':'NO'}</div>`+table(['Symbol','#Share of risk','#Volatility contribution','#Standalone volatility'],RC.by_symbol.slice(0,30).map(x=>`<tr><td>${esc(x.symbol)}</td><td class="n">${pct(x.risk_share_pct,2)}</td><td class="n">${pct(x.vol_contribution_pct,2)}</td><td class="n">${pct(x.standalone_vol_pct,2)}</td></tr>`)):`<div class="muted">${esc(RC.status||'')} (${RC.sessions??0} invested sessions)</div>`;
  const AC=A.account||{};document.getElementById('prf_acct').innerHTML=AC.twr?`<div class="grid">${card('Account return (TWR)',pct(AC.twr.total_return_pct,2),'positions + cash')}${card('Cash',inr(AC.closing_cash),'opening '+inr(AC.opening_cash))}${card('Deposits / withdrawals',inr(AC.deposits)+' / '+inr(AC.withdrawals))}</div><div>${esc(AC.note)}</div>`:esc(AC.note||'');
  const CB=A.contribution;document.getElementById('prf_contrib').innerHTML=`<div class="muted">${esc(CB.method)} · total ${pct(CB.total_pct,3)} · reconciles: ${CB.reconciles?'yes':'NO'}</div><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(300px,1fr))"><div><h3>By symbol</h3>${table(['Symbol','#Gain','#Contribution'],CB.by_symbol.slice(0,30).map(c=>`<tr><td>${esc(c.symbol)}</td><td class="n">${inr(c.gain)}</td><td class="n">${pct(c.contribution_pct,3)}</td></tr>`))}</div><div><h3>By sector</h3>${table(['Sector','#Gain','#Contribution'],CB.by_sector.map(c=>`<tr><td>${esc(c.sector)}</td><td class="n">${inr(c.gain)}</td><td class="n">${pct(c.contribution_pct,3)}</td></tr>`))}<h3>By asset class</h3>${table(['Class','#Gain','#Contribution'],CB.by_asset_class.map(c=>`<tr><td>${esc(c.asset_class)}</td><td class="n">${inr(c.gain)}</td><td class="n">${pct(c.contribution_pct,3)}</td></tr>`))}</div></div>`}
 const S=r.signal_attribution;document.getElementById('prf_sig').innerHTML=`<div class="grid">${card('Signal-driven P&L',inr(S.signal_driven_pnl),S.linked.length+' linked signal(s)')}${card('Discretionary P&L',inr(S.discretionary_pnl),S.discretionary_buys+' buy(s) with no ATIP signal')}${card('Total P&L',inr(S.total_pnl))}</div><div class="muted">${esc(S.source)}</div>`+
  table(['Signal','Entry (delay)','Add-ons','Exits','#Capital','#Actual P&L','#Model ret','#Entry timing','#Averaging','#Exit timing','#Costs','#Sizing','Link · momentum'],S.linked.map(x=>{const a=x.position_attribution||{};return `<tr><td>${esc(x.symbol)}<div class="muted">${esc(x.signal_date)}</div></td><td>${esc(x.entry.date)} @ ${num(x.entry.price)} <span class="muted">(${x.entry.delay_sessions}s)</span></td><td class="muted">${x.add_ons.map(o=>o.date+' '+num(o.quantity,0)+'@'+num(o.price)).join('<br>')}</td><td class="muted">${x.exits.map(o=>o.date+' '+num(o.quantity,0)+'@'+num(o.price)).join('<br>')}${x.open_quantity?'<br>open '+num(x.open_quantity,0):''}</td><td class="n">${inr(x.actual.capital)}</td><td class="n ${x.actual.pnl<0?'bad':'good'}">${inr(x.actual.pnl)}</td><td class="n">${pct(x.model.ret_pct,2)}</td><td class="n">${inr(a.entry_timing)}</td><td class="n">${inr(a.averaging)}</td><td class="n">${inr(a.exit_timing)}</td><td class="n">${inr(a.costs)}</td><td class="n">${x.attribution_vs_model_notional?inr(x.attribution_vs_model_notional.sizing):'—'}</td><td class="muted">${esc(x.link_method||'')} ${(x.momentum_outcomes||[]).map(o=>o.threshold_pct+'%:'+(o.hit?'hit':'no')).join(' ')}</td></tr>`}))+'<div class="muted">entry timing + averaging + exit timing + costs = actual P&L − model P&L on the same quantity; + sizing = actual P&L − model P&L on the model notional. Link: EXACT (the buy carries the signal id) or WINDOW (first buy within the link window).</div>';
 const MT=r.model.trades,ET={};r.executable.trades.forEach(t=>ET[t.signal_id]=t);
 document.getElementById('prf_trades').innerHTML=`<div class="muted">${r.model.signals_in_period} signals · ${r.model.repeats_ignored} repeats ignored · ${r.executable.not_executable} not executable</div>`+table(['Symbol','Signal','#Model entry','Model exit','#Model ret','#Exec entry','#Exec exit','#Exec ret','Status'],MT.map(t=>{const e=ET[t.signal_id]||{};return `<tr><td>${esc(t.symbol)}</td><td>${esc(t.signal_date)}</td><td class="n">${num(t.entry)}</td><td>${esc(t.exit_date)} <span class="muted">${esc(t.exit_reason)}</span></td><td class="n ${t.ret<0?'bad':'good'}">${pct(t.ret==null?null:t.ret*100,2)}</td><td class="n">${e.entry==null?'—':num(e.entry)}</td><td class="n">${e.exit==null?'—':num(e.exit)}</td><td class="n ${e.ret<0?'bad':'good'}">${e.ret==null?'—':pct(e.ret*100,2)}</td><td class="muted">${esc(e.status||'')} ${esc(e.reason||'')}</td></tr>`}));
 const U=r.audit;document.getElementById('prf_audit').innerHTML=`methodology ${esc(U.methodology_version)} · code ${esc(U.calculation_version||'unknown')} · generated ${esc(U.generated_at)}<br>assumptions: ${esc(JSON.stringify(U.assumptions))}<br>inputs: ${esc(JSON.stringify(U.inputs))}`;
}
function prfBody(store){const g=x=>document.getElementById(x).value;const b={portfolio:g('f_pf'),start:g('f_start')||null,end:g('f_end')||null,benchmark:g('f_bm'),store,options:{}};if(g('f_hz')!=='')b.options.horizon=Number(g('f_hz'));if(g('f_slip')!=='')b.options.slippage_bps=Number(g('f_slip'));if(g('f_strat'))b.strategy=g('f_strat');return b}
async function prfRun(store){const b=prfBody(store);
 msg('prf_msg','Computing…');try{prfRender(await post('/api/wealth/performance/report',b));document.getElementById('prf_msg').innerHTML='';prfHist();prfLedger()}catch(e){msg('prf_msg',e.message,1)}}
async function prfPreviewCsv(){const b=prfBody(false);b.format='csv';msg('prf_msg','Computing…');try{const r=await fetch('/api/wealth/performance/report/export',{method:'POST',headers:{'Content-Type':'application/json','X-ATIP-Token':TOKEN},body:JSON.stringify(b)});if(!r.ok)throw new Error((await r.json()).error||r.statusText);const u=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=u;a.download='atip_performance_preview.csv';a.click();URL.revokeObjectURL(u);document.getElementById('prf_msg').innerHTML=''}catch(e){msg('prf_msg',e.message,1)}}
async function prfVerify(id){const el=document.getElementById('prf_verify');el.textContent='Rebuilding from today\'s data…';try{const v=await j('/api/wealth/performance/reports/'+id+'/verify');el.innerHTML=(v.match?'<span class="good">Reproduced exactly</span>':'<span class="bad">Differs</span>: '+esc(v.note))+(v.differences.length?'<br>'+v.differences.slice(0,12).map(d=>esc(d.field)+': '+esc(JSON.stringify(d.stored))+' → '+esc(JSON.stringify(d.now))).join('<br>'):'')}catch(e){el.textContent=e.message}}
async function prfSync(){try{const r=await post('/api/wealth/performance/sync');msg('prf_msg',`Imported: PAPER ${r.PAPER}, OMS ${r.OMS}, LIVE ${r.LIVE}.`);prfLedger()}catch(e){msg('prf_msg',e.message,1)}}
async function prfAddTxn(){const g=x=>document.getElementById(x).value;const b={portfolio:g('x_pf'),trade_date:g('x_date'),kind:g('x_kind')};if(g('x_sym'))b.symbol=g('x_sym');for(const[k,id]of Object.entries({quantity:'x_qty',price:'x_px',fees:'x_fees',gross_value:'x_gross'}))if(g(id)!=='')b[k]=Number(g(id));if(g('x_sig'))b.signal_id=g('x_sig');
 try{await post('/api/wealth/performance/ledger',b);msg('prf_msg','Transaction added.');prfLedger()}catch(e){msg('prf_msg',e.message,1)}}
async function prfVoid(id){const r=prompt('Reason for voiding this transaction (it is kept, marked void):');if(!r)return;try{await post('/api/wealth/performance/ledger/'+id+'/void',{reason:r});prfLedger()}catch(e){msg('prf_msg',e.message,1)}}
async function prfLedger(){const pf=document.getElementById('f_pf').value;const L=await j('/api/wealth/performance/ledger?include_void=true&portfolio='+encodeURIComponent(pf));
 document.getElementById('prf_ledger').innerHTML=table(['Date','Kind','Symbol','#Qty','#Price','#Fees','#Ref','Quality','Source','Note',''],L.slice(-300).reverse().map(t=>`<tr${t.voided_at?' class="muted" style="text-decoration:line-through"':''}><td>${esc(t.trade_date)}</td><td>${esc(t.kind)}</td><td>${esc(t.symbol||'')}</td><td class="n">${t.quantity==null?'—':num(t.quantity,2)}</td><td class="n">${t.price==null?(t.gross_value==null?'—':inr(t.gross_value)):num(t.price)}</td><td class="n">${num(t.fees)}</td><td class="n">${t.reference_price==null?'—':num(t.reference_price)}</td><td class="muted">${esc(t.price_quality||'')}</td><td class="muted">${esc(t.source)}</td><td class="muted" style="font-size:11px">${esc(t.voided_at?'VOID: '+t.void_reason:(t.note||t.tag||''))}</td><td>${t.voided_at?'':`<button onclick="prfVoid('${t.txn_id}')" title="void">✕</button>`}</td></tr>`))}
async function prfOpen(id){prfRender(await j('/api/wealth/performance/reports/'+id))}
async function prfHist(){const H=await j('/api/wealth/performance/reports?limit=20');document.getElementById('prf_hist').innerHTML=table(['Report','Portfolio','Period','Benchmark','Method','Code','Created'],H.map(h=>`<tr><td><a href="#" onclick="prfOpen('${h.report_id}');return false" style="color:var(--accent)">${esc(h.report_id)}</a></td><td>${esc(h.portfolio)}</td><td>${esc(h.period_start)} → ${esc(h.period_end)}</td><td>${esc(h.benchmark)}</td><td>${esc(h.methodology_version)}</td><td class="muted">${esc(h.calculation_version||'')}</td><td>${esc(String(h.created_at).slice(0,16))}</td></tr>`))}
LOADERS.prf=async()=>{
 const P=await j('/api/wealth/performance/portfolios');const sel=document.getElementById('f_pf');
 if(!sel.options.length){const pfs=P.house_book?P.all:['MANUAL'];sel.innerHTML=pfs.map(p=>`<option>${p}</option>`).join('');sel.onchange=prfLedger;
  const B=await j('/api/wealth/performance/benchmarks');document.getElementById('f_bm').innerHTML=Object.entries(B).map(([k,v])=>`<option value="${k}">${v}</option>`).join('');
  const t=new Date(),s=new Date(t-365*864e5);document.getElementById('f_end').value=t.toISOString().slice(0,10);document.getElementById('f_start').value=s.toISOString().slice(0,10);
  if(!P.house_book)document.getElementById('x_pf').innerHTML='<option>MANUAL</option>'}
 prfLedger();prfHist();
 if(!PRF){const H=await j('/api/wealth/performance/reports?limit=1');if(H.length)prfRender(await j('/api/wealth/performance/reports/'+H[0].report_id))}
};
"""

TAB = ("prf", "Performance", HTML, JS)
