"""
Schema scripts for a fresh ATIP database (db/sql/) -- generated by ATIP's own code, never hand-written.

    python tools/schema_sql.py            # rewrite db/sql/atip_schema.postgresql.sql and atip_schema.sqlite.sql
    python tools/schema_sql.py --check    # exit 1 if a checked-in file differs from what the code produces

PostgreSQL is ATIP's one server database (the MySQL backend and its phpMyAdmin export were removed).

HOW. An empty SQLite file is built in a clean subprocess by the same path a first start takes:
init_db() + seed_weights() + ops.migrations.apply() + the tables the order / paper / signal /
strategy / recovery modules create on first use. Then

  atip_schema.postgresql.sql  tools/sqlite_to_postgres.plan() over that file: db.postgres.ddl() for
                              every table and index and trigger_ddl() for the append-only guards --
                              exactly the DDL `tools/sqlite_to_postgres.py --execute` creates
  atip_schema.sqlite.sql      that file's own sqlite_master DDL

each with the seed rows: weight_config (the default scoring weights) and schema_migrations (so
ops.migrations sees the schema as current). Their volatile columns -- weight_config.updated_at,
schema_migrations.applied_at / duration_ms -- are left to the database at load time, which keeps
the output deterministic: tests/test_schema_sql.py requires the checked-in files to match it, so a
schema change that forgets to regenerate them fails the suite instead of shipping stale scripts.

The subprocess runs in an empty temporary directory with ATIP_DATABASE_URL / DATABASE_URL removed,
so neither a local atip_data/config.json nor a configured server can change what is generated.
"""

from __future__ import annotations

import argparse
import os
import re
import sqlite3
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

PG_FILE = ROOT / "db" / "sql" / "atip_schema.postgresql.sql"
SQLITE_FILE = ROOT / "db" / "sql" / "atip_schema.sqlite.sql"

# The start-up path, plus the modules that create their tables on first use rather than in init_db().
_BUILD = r"""
from db.schema import get_connection, init_db, seed_weights
init_db()
seed_weights()
from ops import migrations
from orders import broker, paper, rules
from pipeline import recover
from scores import signal_log
from strategy import positions
c = get_connection()
try:
    failed = [r for r in migrations.apply(c) if r["status"] != "APPLIED"]
    if failed:
        raise SystemExit(f"migrations did not apply: {failed}")
    rules._ensure_table(c)
    broker._ensure_order_log_table(c)
    paper.ensure_tables(c)
    signal_log.ensure_tables(c)
    positions.ensure_tables(c)
    recover.ensure_table(c)
    c.commit()
finally:
    c.close()
"""

# table -> (columns left out so the database fills them, columns written as CURRENT_TIMESTAMP)
SEEDS = {
    "schema_migrations": (("duration_ms",), ("applied_at",)),
    "weight_config": (("updated_at",), ()),
}


def build_fresh(path: Path) -> None:
    """An empty ATIP database at `path`, made by ATIP's own start-up code."""
    env = {k: v for k, v in os.environ.items() if k not in ("ATIP_DATABASE_URL", "DATABASE_URL")}
    env["ATIP_DB_PATH"] = str(path)
    env["PYTHONPATH"] = str(ROOT) + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    with tempfile.TemporaryDirectory() as cwd:                  # no atip_data/config.json to read
        r = subprocess.run([sys.executable, "-c", _BUILD], env=env, cwd=cwd, capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError(f"building a fresh database failed:\n{r.stderr[-3000:]}")


def _literal(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'" + str(v).replace("'", "''") + "'"


def seed_sql(conn: sqlite3.Connection) -> tuple[list[str], dict]:
    """INSERT statements valid on both SQLite and PostgreSQL, and {table: rows}."""
    out, counts = [], {}
    for table, (omit, now) in SEEDS.items():
        cols = [r[1] for r in conn.execute(f'PRAGMA table_info("{table}")') if r[1] not in omit]
        pk = [r[1] for r in sorted(conn.execute(f'PRAGMA table_info("{table}")'), key=lambda r: r[5]) if r[5]]
        rows = conn.execute(f'SELECT {",".join(cols)} FROM "{table}" ORDER BY {",".join(pk)}').fetchall()
        counts[table] = len(rows)
        if not rows:
            continue
        values = ",\n".join("  (" + ", ".join("CURRENT_TIMESTAMP" if c in now else _literal(v)
                                              for c, v in zip(cols, row)) + ")" for row in rows)
        out.append(f"INSERT INTO {table} ({', '.join(cols)}) VALUES\n{values};")
    return out, counts


def _header(lines: list[str]) -> str:
    bar = "-- " + "=" * 69
    return "\n".join([bar] + [("-- " + x).rstrip() for x in lines] + [bar]) + "\n"


def render(source: Path) -> tuple[str, str]:
    """(PostgreSQL script, SQLite script) for the fresh database at `source`."""
    from tools.sqlite_to_postgres import plan
    p = plan(source)
    if p["skipped"]:
        raise RuntimeError(f"objects with no PostgreSQL translation: {p['skipped']}")
    c = sqlite3.connect(f"file:{source.as_posix()}?mode=ro", uri=True)
    try:
        objs = c.execute("SELECT type, name, sql FROM sqlite_master WHERE sql IS NOT NULL AND name NOT LIKE "
                         "'sqlite_%' ORDER BY CASE type WHEN 'table' THEN 0 WHEN 'index' THEN 1 ELSE 2 END, name"
                         ).fetchall()
        seeds, counts = seed_sql(c)
    finally:
        c.close()
    n = {k: sum(1 for t, _, _ in objs if t == k) for k in ("table", "index", "trigger")}
    seeded = ", ".join(f"{t} ({k})" for t, k in counts.items())
    what = (f"{n['table']} tables, {n['index']} indexes, {n['trigger']} append-only triggers, "
            f"and seed rows: {seeded}.")
    regen = ["GENERATED by tools/schema_sql.py from ATIP's own code (init_db() + seed_weights()",
             "+ ops.migrations.apply() + the tables created on first use). Do not edit by hand:",
             "change the code and run `python tools/schema_sql.py`."]

    identity = [t for t in SEEDS if re.search(rf"CREATE TABLE IF NOT EXISTS {t} \([^;]*\bid BIGINT GENERATED",
                                              "\n".join(p["ddl"]))]
    pg = _header(
        ["ATIP -- atip_schema.postgresql.sql   (PostgreSQL 16; ATIP's server database)", ""] + regen +
        ["", what, "",
         "  createdb atip",
         "  psql -d atip -v ON_ERROR_STOP=1 -f db/sql/atip_schema.postgresql.sql",
         "",
         "Into an EMPTY database. Then switch ATIP over as docs/POSTGRESQL_MIGRATION.md",
         "says (ATIP_DATABASE_URL + config.json \"database\": {\"backend\": \"postgresql\",",
         "\"allow_experimental\": true}). To move EXISTING data use",
         "tools/sqlite_to_postgres.py on a backup copy, not this file."])
    pg += "\nBEGIN;\n\n" + "\n\n".join(p["ddl"]) + "\n\n-- ---- seed data ----\n" + "\n\n".join(seeds) + "\n"
    for t in identity:                     # explicit ids were inserted: new rows must not reuse them
        pg += (f"\nSELECT setval(pg_get_serial_sequence('{t}', 'id'), "
               f"COALESCE((SELECT MAX(id) FROM {t}), 0) + 1, false);\n")
    pg += "\nCOMMIT;\n"

    lite = _header(
        ["ATIP -- atip_schema.sqlite.sql   (SQLite: the default runtime)", ""] + regen +
        ["", what, "",
         "You normally DON'T need this: ATIP creates its own database on first",
         "start (python main.py). Use it to pre-build atip_data/atip.db:",
         "    sqlite3 atip_data/atip.db < db/sql/atip_schema.sqlite.sql",
         "Only for a NEW, empty file. Never run against the live atip.db."])
    lite += "PRAGMA foreign_keys=OFF;\nBEGIN TRANSACTION;\n"
    for kind, label in (("table", "tables"), ("index", "indexes"), ("trigger", "triggers")):
        lite += f"\n-- ---- {label} ----\n" + "\n".join(sql.strip() + ";" for t, _, sql in objs if t == kind) + "\n"
    lite += "\n-- ---- seed data ----\n" + "\n\n".join(seeds) + "\nCOMMIT;\n"
    return pg, lite


def generate() -> tuple[str, str]:
    with tempfile.TemporaryDirectory() as d:
        db = Path(d) / "atip.db"
        build_fresh(db)
        return render(db)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--check", action="store_true", help="compare with the checked-in files; write nothing")
    a = ap.parse_args(argv)
    pg, lite = generate()
    stale = [f for f, text in ((PG_FILE, pg), (SQLITE_FILE, lite))
             if not f.exists() or f.read_text(encoding="utf-8") != text]
    if a.check:
        for f in stale:
            print(f"stale: {f.relative_to(ROOT)} (run: python tools/schema_sql.py)")
        return 1 if stale else 0
    for f, text in ((PG_FILE, pg), (SQLITE_FILE, lite)):
        f.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {f.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
